/* barangay selection */
export default // [
//   "Alima",
//   "Aniban I",
//   "Aniban II",
//   "Aniban III",
//   "Aniban IV",
//   "Aniban V	 ",
//   "Banalo	 ",
//   "Campo Santo",
//   "Daang Bukid	",
//   "Digman	 	 ",
//   "Dulong Bayan",
//   "Habay I	  ",
//   "Habay II	 ",
//   "Kaingin	 ",
//   "Ligas I	 	 ",
//   "Ligas II	 ",
//   "Ligas III	 ",
//   "Mabolo I	 ",
//   "Mabolo II	 ",
//   "Mabolo III	 ",
//   "Maliksi I	 ",
//   "Maliksi II	 ",
//   "Maliksi III	 ",
//   "Mambog I	 ",
//   "Mambog II	 ",
//   "Mambog III	 ",
//   "Mambog IV	 ",
//   "Mambog V	 ",
//   "Molino I	 ",
//   "Molino II	 ",
//   "Molino III	 ",
//   "Molino IV	 ",
//   "Molino V	 ",
//   "Molino VI	 ",
//   "Molino VII	 ",
//   "Niog I	  ",
//   "Niog II	 ",
//   "Niog III	 ",
//   "P.F. Espiritu I ",
//   "P.F. Espiritu II	 ",
//   "P.F. Espiritu III	 ",
//   "P.F. Espiritu IV	 ",
//   "P.F. Espiritu V	 ",
//   "P.F. Espiritu VI	 ",
//   "P.F. Espiritu VII	 ",
//   "P.F. Espiritu VIII	 ",
//   "Queens Row Central	 ",
//   "Queens Row East	 	 ",
//   "Queens Row West	 	 ",
//   "Real I	 	 ",
//   "Real II	 	 ",
//   "Salinas I	 ",
//   "Salinas II	 ",
//   "Salinas III ",
//   "Salinas IV	 ",
//   "San Nicolas I",
//   "San Nicolas II	",
//   "San Nicolas III	",
//   "Sineguelasan	 ",
//   "Tabing Dagat	 ",
//   "Talaba I	  ",
//   "Talaba II	 ",
//   "Talaba III	 ",
//   "Talaba IV	 ",
//   "Talaba V	 ",
//   "Talaba VI	 ",
//   "Talaba VII	 ",
//   "Zapote I	 ",
//   "Zapote II	 ",
//   "Zapote III	 ",
//   "Zapote IV	 ",
// ];

[
  "Poblacion 1 (Area I)",
  "Poblacion 2 (Area I)",
  "Poblacion 3 (Area I)",
  "Poblacion 4 (Area I)",
  "Poblacion 5 (Area G)",
  "Benjamin Tirona (Area D)",
  "Benjamin Pulido (Area H)",
  "Epifanio Malia (Area D)",
  "Francisco De Castro (Formerly Area B)",
  "Francisco Reyes (Formerly Area A)(Metro San Jose)",
  "Fiorello Calimag (Area C)",
  "Gavino Maderan (Area J)",
  "Gregoria De Jesus (Formerly Area A)(Metro San Jose)",
  "Inocencio Salud (Area F)",
  "Jacinto Lumbreras (Area J)",
  "Kapitan Kua (Area F)",
  "Koronel Jose P. Elises (Area E)",
  "Macarioi Dacon (Area D)",
  "Marcelino Memije (Area H)",
  "Nicolasa Virata (Formerly Area A)(Metro San Jose)",
  "Pantaleon Granados (Area K)",
  "Ramon Cruz Sr. (Area J)",
  "San Gabriel (Area K)",
  "San Jose (Formerly Area A)(Metro San Jose)",
  "Severino De Las Alas (Area J)",
  "Tiniente Tiago (Formerly Area A)(Metro San Jose)",
];
